title: Grissom's Docs
description: Docs for Grissom
theme: just-the-docs # using .github\workflows\pages.ymll defined action
# remote_theme: just-the-docs/just-the-docs # uncomment when using github's action of  pages-builld-deployment 

url: https://grissomlau.github.io

aux_links:
   My GitHub: https://github.com/grissomlau
